# Basic Python

 1. Split this string

In [4]:
s = "Hi there Sam!" 

In [5]:
s=s.split()
print(s)


['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [6]:
planet = "Earth"
diameter = 12742

In [7]:
print("The diameter of {0} is {1} kilometers".format(planet, diameter))

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [9]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [30]:
print(d)

{'k1': [1, 2, 3, {'tricky': ['oh', 'man', 'inception', {'target': [1, 2, 3, 'hello']}]}]}


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [13]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [12]:
import numpy as np
array=np.arange(20,35,2)
print("Array of all the even integers from 30 to 70")
print(array) 

Array of all the even integers from 30 to 70
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [16]:
import numpy as np

a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

arr = np.concatenate((a, b))

print(arr)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [25]:
import pandas as pd


In [29]:
import pandas as pd
  
# initialize data of lists.
data = {'Name': ['sri', 'vatsan'],
        'Age': [20, 21],
        'Gender':['M','M']}
  
# Create DataFrame
df = pd.DataFrame(data)
  
# Print the output.
df

Name  Age Gender
0     sri   20      M
1  vatsan   21      M

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [17]:
import datetime
import pandas as pd
start = datetime.datetime.strptime("01-01-2023", "%d-%m-%Y")
end = datetime.datetime.strptime("10-2-2023", "%d-%m-%Y")
date_generated = pd.date_range(start, end)

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [22]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [23]:

import pandas as pd  
      

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
      
df = pd.DataFrame(lists, columns =['NO', 'Name', 'Size'],
                                          ) 
print(df)

   NO Name  Size
0   1  aaa    22
1   2  bbb    25
2   3  ccc    24
